name: Image building and testing on Linux

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to OpenVINO package'
        required: true
        default: ''
      distribution:
        description: 'Distribution for OpenVINO package: dev, runtime, data_dev, proprietary'
        required: true
        default: 'dev'
      os:
        description: 'Operation System for docker image: ubuntu18, ubuntu20'
        required: true
        default: 'ubuntu18'
      args:
        description: 'Additional arguments'
        required: false
        default: ''

jobs:
  build_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Build and test image
        run: python docker_openvino.py build_test --dist ${{ inputs.distribution }} -os ${{ inputs.os }} --package_url ${{ inputs.package_url }} -k cpu ${{ inputs.args }}
      - name: Checking resulting image
        if: ${{ always() }}
        run: docker images
      - name: Collecting artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            logs/
            ./*.html
            ./*.log
