name: Codestyle checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  codestyle:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Setting up Python codestyle checks/test dependencies
        run: >
          python -m pip install flake8 flake8-annotations-complexity flake8-bandit flake8-broken-line bandit
          flake8-bugbear flake8-comprehensions flake8-debugger flake8-eradicate flake8-executable flake8-print mypy
          flake8-string-format flake8_builtins flake8_coding flake8_commas flake8_pep3101 flake8_quotes import-order
          naming radon flake8-rst-docstrings more-itertools packaging pluggy py pytest pytest-html pytest-metadata

      - name: Running Bandit
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: python -m bandit -r ./ -f screen
          
      - name: Running PEP checks
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: python -m flake8 ./ --config=setup.cfg --show-source

      - name: Running MyPy checks
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: python -m mypy ./ --config-file ./setup.cfg --show-error-context --show-column-numbers --pretty

      - name: Running pytest (not Docker image tests)
        if: ${{ always() }}
        run: python -m pytest ./utils/tests
