# This is a basic workflow to help you get started with Actions

name: Master branch update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
#   pull_request:
#     branches: [ master ]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
#       - name: Checking repo
#         run: ls -lAh
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python codestyle check dependencies
        run: >
          python -m pip install flake8 flake8-annotations-complexity flake8-bandit flake8-broken-line flake8-bugbear 
          flake8-comprehensions flake8-debugger flake8-eradicate flake8-executable flake8-print flake8-string-format 
          flake8_builtins flake8_coding flake8_commas flake8_isort flake8_pep3101 flake8_quotes import-order 
          flake8-logging-format naming radon flake8-rst-docstrings more-itertools packaging pluggy py mypy
      - name: Running Python codestyle checks
#         if: ${{ always() }}
        run: |
          flake8 --output-file=flake8_check.log .
          mypy . > mypy_check.log

      - name: Collecting log artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/
      - name: Collecting codestyle artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: codestyle_checks
          path: ./*_check.log
