name: Image publishing on Windows

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to OpenVINO package'
        required: true
        default: ''
      distribution:
        description: 'Distribution for OpenVINO package: dev, runtime, data_dev'
        required: true
        default: ''
      os:
        description: 'Operation System for docker image: winserver2019'
        required: true
        default: 'winserver2019'
      args:
        description: 'Additional arguments'
        required: false
        default: ''

jobs:
  publish:
    runs-on: windows-2019
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Docker login to registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build and publish image
#        run: python docker_openvino.py all --dist ${{ inputs.distribution }} -os ${{ inputs.os }} --package_url ${{ inputs.package_url }} --nightly -r openvino ${{ inputs.args }}
#      - name: Checking resulting image
#        run: docker images
#
#      - name: Collecting artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: logs
#          path: |
#            logs/
#            ./*.html
#            ./*.log