name: Image publishing

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to OpenVINO package'
        required: true
        default: 'https://registrationcenter-download.intel.com/akdlm/irc_nas/16803/l_openvino_toolkit_p_2020.4.287.tgz'