name: Image publishing

on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to OpenVINO package'
        required: true
        default: ''
      distribution:
        description: 'Distribution for OpenVINO package: dev, runtime'
        required: true
        default: ''
      os:
        description: 'Operation System for docker image: ubuntu18, ubuntu20, winserver2019'
        required: true
        default: ''
      slave:
        description: 'Slave to build docker image: ubuntu-18.04, windows-2019'
        required: true
        default: ''
      args:
        description: 'Additional arguments'
        required: false
        default: ''

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
        include:
          - os: ubuntu-18.04
            cli_opts: ''
          - os: windows-2019
            cli_opts: ''
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Docker login to registry
        if: ${{ matrix.os == slave }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build and publish image
#        if: ${{ matrix.os == slave }}
#        run: python docker_openvino.py all --dist ${{ distribution }} --source url --install_type copy -os ${{ os }} --package_url ${{ package_url }} --nightly -r openvino ${{ args }} ${{ matrix.cli_opts }}
#      - name: Checking resulting image
#        if: ${{ matrix.os == slave }}
#        run: docker images
#
#      - name: Collecting artifacts
#        if: ${{ matrix.os == slave }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: logs
#          path: |
#            logs/
#            ./*.html
#            ./*.log