name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      package_url:
        description: 'URL to OpenVINO package'
        required: true
        default: 'https://registrationcenter-download.intel.com/akldm/irc_nas/16803/l_openvino_toolkit_p_2020.4.287.tgz'
#       home:
#         description: 'location'
#         required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
#       - name: Checking repo
#         run: ls -lAh
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python dependencies
        run: python -m pip install -r requirements.txt
#       - name: Pinging Docker daemon
#         run: docker info
      - name: Generating Dockerfile
        run: python docker_openvino.py build --dist proprietary --source url --install_type install --package_url ${{ github.event.inputs.package_url }}
#       - name: Pinging Docker daemon from Python
#         run: python actions_docker_test.py
      - name: Checking resulting image
        if: ${{ always() }}
        run: docker images

      - name: Collecting artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/
#       - name: Collecting Dockerfiles
#         if: ${{ always() }}
#         uses: actions/upload-artifact@v2
#         with:
#           name: dockerfiles
#           path: dockerfiles/
